### ISSUE TITLE
Publish to npm

### ISSUE THREAD

**Issue by englercj** [grapefruitjs/grapefruit#73]
DO IT

**Comment by potomak** [comment]
I think that this issue is related to https://github.com/GoodBoyDigital/pixi.js/issues/307

**Comment by englercj** [comment]
In what way?

**Comment by potomak** [comment]
Before publishing this package to npm I think you should list pixi.js as a dependency in `package.json` but pixi.js can't be listed as a dependency as soon as https://github.com/GoodBoyDigital/pixi.js/issues/307 is open.

**Comment by englercj** [comment]
I don't pull pixi in via  package manager, I pull the compiled file into my vendor folder; so it isn't an npm dependency. Npm would report errors if I placed it there.

**Comment by potomak** [comment]
Ok then...

**Comment by englercj** [comment]
I have released grapefruit into `npm` and `bower`. Enjoy!

**Comment by drkibitz** [comment]
@englercj Did you mean pixi.js as well?
https://npmjs.org/package/pixi.js

Side note, I am still maintaining my fork: https://npmjs.org/package/pixi

I saw in another thread this was brought up, should I rename the package to "node-pixi"? I wasn't thinking it would conflict with anything, I was just under the assumption that the "Pixi.JS" package that was on there would remain as such, and there's a long of packages named "node-something" on git, and just "something" on npm. That's where that comes from.

**Comment by englercj** [comment]
I did release pixi as well, but that is not what I meant when I posted that comment :)

I'm fine with you keeping your fork, and name it whatever you feel is appropriate. I went with pixi.js since pixi was taken on npm, but both our packages (npm/bower) are pixi.js now and that is fine.

**Comment by drkibitz** [comment]
Oh crap! I didn't even notice I was on a grapefruit repo, how did github search send me here?!
Sorry

**Comment by englercj** [comment]
Hehe no problem!
