### ISSUE TITLE
0.2 builds

### ISSUE THREAD

**Issue by krazyjakee** [grapefruitjs/grapefruit#93]
I've tried unsuccessfully to get grunt running on windows 8. Is there any chance you can list the downloadable files gf.js and min versions like previous releases?

https://github.com/grapefruitjs/grapefruit/releases/tag/v0.2.0

Thanks

**Comment by englercj** [comment]
Oops! Thought I had uploaded them! I am running on windows 8 though, what are your issues running the build?

**Comment by krazyjakee** [comment]
There's no issue with the build, it's with grunt itself.

```
grunt-cli: The grunt command line interface. (v0.1.13)
Fatal error: Unable to find local grunt.
```

I've uninstalled packages, re installed, set environment variables and nothing has fixed the problem.

**Comment by englercj** [comment]
Uploaded the builds to the release page: https://github.com/grapefruitjs/grapefruit/releases/tag/v0.2.0

That issue occurs when grunt is not installed in the local project you are running the grunt-cli from. Make sure you are in the grapefruit folder and you have installed all the packages for gf locally. (meaning there is a `node_modules` folder in the grapefruit project, and it has a `grunt` subfolder). Should be something like this:

``` shell
npm i -g grunt-cli
cd /path/to/where/you/cloned/grapefruit
npm i
grunt
```

**Comment by krazyjakee** [comment]
I can confirm a successful build with those commands, thanks.
