### ISSUE TITLE
0.2 Scale modes

### ISSUE THREAD

**Issue by krazyjakee** [grapefruitjs/grapefruit#94]
I have this line in my code:
`gf.Texture.SCALE_MODE.DEFAULT = gf.Texture.SCALE_MODE.NEAREST`

SCALE_MODE seems not to exist any more.
Is scale mode set to nearest by default now?

**Comment by englercj** [comment]
PIXI reorganized their constants, it is now under `gf.PIXI.scaleModes`. Your line should now be:

```
gf.PIXI.scaleModes.DEFAULT = gf.PIXI.scaleModes.NEAREST;
```
